// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/wallet/connect.ts";
import * as $2 from "./routes/api/wallet/disconnect.ts";
import * as $3 from "./routes/api/wallet/setAccount.ts";
import * as $4 from "./routes/create-multisig.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/AccountSelect.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/wallet/connect.ts": $1,
    "./routes/api/wallet/disconnect.ts": $2,
    "./routes/api/wallet/setAccount.ts": $3,
    "./routes/create-multisig.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/AccountSelect.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
